name = "SyslogLogging"
uuid = "0c4b0c42-68ec-11ea-3bc9-e7fb6e00ea0f"
keywords = ["syslog", "logger"]
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
license = "MIT"
desc = "Syslog Logger for Julia"
version = "0.1.0"

[deps]
Syslogs = "cea106d9-e007-5e6c-ad93-58fe2094e9c4"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "~1"
Syslogs = "~0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
